library(profileplyr)
library(soGGi)
context("Test import from soGGi")
data(chipExampleBig)
p <- as_profileplyr(chipExampleBig,names = "name")

expect_true(is(p,"profileplyr"))
expect_true(length(p) == 201)
expect_true(ncol(p) == 300)
expect_true(nrow(sampleData(p)) == 10)
expect_true(params(p)$rowGroupsInUse == "sgGroup")