library(profileplyr)
library(soGGi)
context("Test import from soGGi")
data(chipExampleBig)
p <- as_profileplyr(chipExampleBig,names = "name")
expect_that(is(p,"profileplyr"),is_true())
expect_that(length(p) == 201,is_true())
expect_that(ncol(p) == 300,is_true())
expect_that(nrow(sampleData(p)) == 10,is_true())
expect_that(params(p)$rowGroupsInUse == "sgGroup",is_true())
