library(profileplyr)
library(soGGi)
context("Test subsetting and indexing")
example <- system.file("extdata", "example_deepTools_MAT", package = "profileplyr") 
object <- import_deepToolsMat(example)
expect_true(is(object,"profileplyr"))
expect_true(length(object) == 400)
expect_true(ncol(object) == 25)
expect_true(nrow(sampleData(object)) == 3)
expect_true(params(object)$rowGroupsInUse == "dpGroup")
