library(profileplyr)
library(soGGi)
context("Test subsetting and indexing")
data(chipExampleBig)
p <- as_profileplyr(chipExampleBig,names = "name")
export_deepToolsMat(p,con = "p.MAT")
export_deepToolsMat(p[,,1],con = "pSingle.MAT")
expect_true(file.exists("p.MAT.gz"))
expect_true(file.exists("pSingle.MAT.gz"))
unlink("p.MAT.gz")
unlink("pSingle.MAT.gz")
