library(profileplyr)
library(soGGi)
context("Test subsetting and indexing")
example <- system.file("extdata", "example_deepTools_MAT", package = "profileplyr") 
object <- import_deepToolsMat(example)
expect_that(is(object,"profileplyr"),is_true())
expect_that(length(object) == 400,is_true())
expect_that(ncol(object) == 25,is_true())
expect_that(nrow(sampleData(object)) == 3,is_true())
expect_that(params(object)$rowGroupsInUse == "dpGroup",is_true())
